#export PLANTY_SMTP_USERNAME="AKIAIY2FEPOYOLLQOTLQ"
#export PLANTY_SMTP_PASSWORD="Av6xBdXDa2si0cPOk1dVp5apuE+cLZ/Eq7y9vIpS67O+"
export PLANTY_SMTP_USERNAME="AKIA5AHF4GHN275ONPOP"
export PLANTY_SMTP_PASSWORD="BNb+tOZykyox4kScvvDILAUUK2/tVlATi/6/QiRZtTxy"
